# Name : Mohammad Sabik Irbaz
# Student ID : 160041004
# CSE 4739 : Data Mining
# Assignment : 02
# Task : 03

In [3]:
import numpy as np
import math

In [13]:
# Initialization
X = np.array([(0,0),(1,2),(1,3),(2,2),(2,3),(3,3),(6,8),(4,8)])
k = 3
X.shape, k

((8, 2), 3)

**Step 1 : Finding the distance between every pair or coordinates**

In [12]:
# This function finds out the Manhattan distance between the a and b coordinates
def dist(a, b):
  return np.sum(np.abs(a-b))

In [19]:
dis = []

for i in range(X.shape[0]):
  cur = []
  for j in range(X.shape[0]):
    cur.append(dist(X[i],X[j]))
  cur = np.asarray(cur)
  dis.append(cur)

dis = np.asarray(dis)
dis

array([[ 0,  3,  4,  4,  5,  6, 14, 12],
       [ 3,  0,  1,  1,  2,  3, 11,  9],
       [ 4,  1,  0,  2,  1,  2, 10,  8],
       [ 4,  1,  2,  0,  1,  2, 10,  8],
       [ 5,  2,  1,  1,  0,  1,  9,  7],
       [ 6,  3,  2,  2,  1,  0,  8,  6],
       [14, 11, 10, 10,  9,  8,  0,  2],
       [12,  9,  8,  8,  7,  6,  2,  0]])

**Step - 2 : Finding the k-th nearest neighbor distance from each coordinate**

In [32]:
knnd = []

for i in range (dis.shape[0]):
  cur = dis[i]
  cur = np.sort(cur)
  knnd.append(cur[3])

knnd = np.asarray(knnd)
knnd

array([4, 2, 2, 2, 1, 2, 9, 7])

**Step - 3 : Finding the k distance neighborhood of each coordinate**

In [28]:
knn = []

for i in range (dis.shape[0]):
  cn = []
  for j in range (dis.shape[1]):
    if knnd[i] >= dis[i][j] and i != j :
      cn.append(j)
  cn = np.asarray(cn)
  knn.append(cn)

knn = np.asarray(knn)
knn

array([array([1, 2, 3]), array([2, 3, 4]), array([1, 3, 4, 5]),
       array([1, 2, 4, 5]), array([2, 3, 5]), array([2, 3, 4]),
       array([4, 5, 7]), array([4, 5, 6])], dtype=object)

**Step- 4 : Calculating local reachability distance for each coordinate**

In [45]:
# reachdist(a,b) : reachability distance from b to a
def reachdist(a,b):
  return max(knnd[b],dis[a][b])

In [49]:
lrd = []

for i in range (knn.shape[0]):
  sum = 0
  for j in range (knn[i].shape[0]):
    sum += reachdist(i,knn[i][j])
  cr = knn[i].shape[0]/sum
  lrd.append(cr)

lrd = np.asarray(lrd)
lrd

array([0.27272727, 0.5       , 0.57142857, 0.57142857, 0.5       ,
       0.6       , 0.125     , 0.13636364])

**Step- 5 : Calculating local outlier factor (LOF) for each coordinate**

In [50]:
LOF = []

for i in range(lrd.shape[0]):
  sum = 0
  for j in range(knn[i].shape[0]):
    sum += lrd[knn[i][j]]/lrd[i]
  cl = sum/knn[i].shape[0]
  LOF.append(cl)

LOF = np.asarray(LOF)
LOF

array([2.00793651, 1.0952381 , 0.95      , 0.95      , 1.16190476,
       0.91269841, 3.2969697 , 2.99444444])

**Step - 6 : Identifying potential outliers**

In [51]:
outliers = []

for i in range(LOF.shape[0]):
  if LOF[i] >= 1.5 :
    outliers.append(X[i])

outliers = np.asarray(outliers)
outliers

array([[0, 0],
       [6, 8],
       [4, 8]])